import { GiSkills } from "react-icons/gi";

const projectList = [
    { id: 1, title: "Emerald Park", description: "A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map.", full_description: " A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map.",  link: "/project/1", imageUrl: '/my-portfolio/img/emeraldpark.png', websiteUrl: 'https://emerald-park.azurewebsites.net/', technologies: ['Java', 'JavaScript', 'Bootstrap', 'MySQL', 'Azure', 'GitHub', 'Figma'], skills: ['Full Stack Development', 'Database Design', 'User Authentication', 'UX Design', 'Payment Processing'] },
    { id: 2, title: "Fund Fairy", description: "A collaborative Laravel PHP project for a fictional crowd funding platform with users and donations.", full_description: " A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map.", link: "/project/2", imageUrl: '/my-portfolio/img/fundfairy.png', websiteUrl: 'https://fundfairy.live' , technologies: ['PHP', 'Laravel', 'Tailwind', 'GitHub', 'Heroku', 'Figma'], skills: ['Collaboration', 'Communication', 'Version Control', 'Database Design', 'UX Design'] },
    { id: 3, title: "Optimist Club", description: "A functional website for a local youth organization using Wordpress / Elementor.", full_description: " A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map. A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map.", link: "/project/3", imageUrl: '/my-portfolio/img/optimist.png', websiteUrl: 'https://optimistnl.org/' , technologies: ['Wordpress', 'Elementor', 'MySQL', 'JavaScript'], skills: ['Communication', 'Collaboration', 'UX Design', 'Accessibility', 'User Authentication']  },
];

export default projectList;
