import { GiSkills } from "react-icons/gi";

const projectList = [
    { id: 1, title: "Emerald Park", description: "A robust Java website for a fictional park, including user authentication, filtering, and an interactive trail map.", fullDescription: "For my final project in my three-semester Java course, I made a fully functional park website for trail management. The idea first came to me in my MySQL database course, where we designed and wrote the scripts for an idea. From the beginning, I had a vision for this project. I brought the project to life using full-stack Java development, including Java Servlets and JSPs for the backend and front-end logic. Features include user authentication, interactive trail maps, trail navigation and filtering, trail reviews, maintenance logging, donations with payment processing, and user dashboards.  I also prioritized a modern, accessible UI that captured the adventurous spirit of this fictional park. This project challenged and grew my skills in web development and project management.",  link: "/project/1", imageUrl: '/my-portfolio/img/emeraldpark.png', layoutUrl: '/my-portfolio/img/emeraldparklayout.png', websiteUrl: 'https://emerald-park.azurewebsites.net/', technologies: ['Java', 'JavaScript', 'Bootstrap', 'MySQL', 'Azure', 'GitHub', 'Figma'], skills: ['Full Stack Development', 'Database Design', 'User Authentication', 'UX Design', 'Payment Processing'] },
    { id: 2, title: "Fund Fairy", description: "A collaborative Laravel PHP project for a fictional crowd funding platform with users and donations.", fullDescription: "For my Web Technologies Capstone class, we were instructed to design and build a website for a crowdfunding platform. In a group of 7 students, we worked to make FundFairy come to life. We used Laravel PHP to construct this website. The project utilizes the Laravel MVC (Model, View, Controller) structure to create, read, update, and delete multiple objects. We worked together to visually design and implement user login and register, user authentication, dashboard, create and edit donations and donation requests, and more. I have gained a lot of experience collaborating with my peers and problem-solving in a team environment. ", link: "/project/2", imageUrl: '/my-portfolio/img/fundfairy.png', layoutUrl: '/my-portfolio/img/fundfairylayout.png', websiteUrl: 'https://fundfairy.live' , technologies: ['PHP', 'Laravel', 'Tailwind', 'GitHub', 'Heroku', 'Figma'], skills: ['Collaboration', 'Communication', 'Version Control', 'Database Design', 'UX Design'],  },
    { id: 3, title: "Optimist Club", description: "A functional website for a local youth organization using Wordpress / Elementor.", fullDescription: "I had the honor of working with a local youth organization in my area called the Optimist Club of North Liberty. The club works to raise money for youth clubs and events. They had a very outdated website that was difficult to navigate and for the members to maintain. They employed me to improve their site visually and functionally. I used Wordpress and Elementor to make a fully functional website for people in the area as well as their members to use and see exclusive content. I was able to work one on one with the client and to exchange feedback to improve the website. This was an extremely rewarding experience, and I am so grateful to have helped out this wonderful organization.", link: "/project/3", imageUrl: '/my-portfolio/img/optimist.png', layoutUrl: '/my-portfolio/img/optimistlayout.png', websiteUrl: 'https://optimistnl.org/' , technologies: ['Wordpress', 'Elementor', 'MySQL', 'JavaScript'], skills: ['Communication', 'Collaboration', 'UX Design', 'Accessibility', 'User Authentication']  },
];

export default projectList;
